"""empty message

Revision ID: 318dd7d0bb4b
Revises: 823e01411296
Create Date: 2026-03-27 12:05:06.960852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '318dd7d0bb4b'
down_revision: Union[str, Sequence[str], None] = '823e01411296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paymentorder_order_id'))
        batch_op.drop_index(batch_op.f('ix_paymentorder_user_id'))

    op.drop_table('paymentorder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentorder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(), nullable=False),
    sa.Column('plan', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('payhere_payment_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paymentorder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paymentorder_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paymentorder_order_id'), ['order_id'], unique=1)

    # ### end Alembic commands ###
