"""empty message

Revision ID: 31d7a7907624
Revises: 000b7edf28ba
Create Date: 2026-02-26 03:02:21.079212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '31d7a7907624'
down_revision: Union[str, Sequence[str], None] = '000b7edf28ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_premium_1', sa.Boolean(), nullable=False),
    sa.Column('is_premium_2', sa.Boolean(), nullable=False),
    sa.Column('daily_message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userprofile_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userprofile_user_id'))

    op.drop_table('userprofile')
    # ### end Alembic commands ###
