"""empty message

Revision ID: 39090ce2ddc2
Revises: 31d7a7907624
Create Date: 2026-02-26 03:38:53.617737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '39090ce2ddc2'
down_revision: Union[str, Sequence[str], None] = '31d7a7907624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payhere_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paymentorder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paymentorder_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_paymentorder_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paymentorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paymentorder_user_id'))
        batch_op.drop_index(batch_op.f('ix_paymentorder_order_id'))

    op.drop_table('paymentorder')
    # ### end Alembic commands ###
