"""empty message

Revision ID: 5ed222f79f8b
Revises: 318dd7d0bb4b
Create Date: 2026-04-02 23:04:41.288284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5ed222f79f8b'
down_revision: Union[str, Sequence[str], None] = '318dd7d0bb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermemory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pathway', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('active_subject', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermemory', schema=None) as batch_op:
        batch_op.drop_column('active_subject')
        batch_op.drop_column('pathway')

    # ### end Alembic commands ###
