"""empty message

Revision ID: 823e01411296
Revises: 
Create Date: 2026-03-14 18:41:20.859157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '823e01411296'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermemory', schema=None) as batch_op:
        batch_op.drop_column('active_scope')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermemory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_scope', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
