"""empty message

Revision ID: 960c239263d9
Revises: b09a7b6984f2
Create Date: 2026-02-23 01:31:16.377838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '960c239263d9'
down_revision: Union[str, Sequence[str], None] = 'b09a7b6984f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scopememory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scopememory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scopememory_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_scopememory_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'home'"), nullable=False))
        batch_op.create_index(batch_op.f('ix_chatsession_scope'), ['scope'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatsession_scope'))
        batch_op.drop_column('scope')

    with op.batch_alter_table('scopememory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scopememory_user_id'))
        batch_op.drop_index(batch_op.f('ix_scopememory_scope'))

    op.drop_table('scopememory')
    # ### end Alembic commands ###
