"""empty message

Revision ID: abe3e86bbe6d
Revises: c49a14b5d311
Create Date: 2026-03-09 07:57:50.274279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'abe3e86bbe6d'
down_revision: Union[str, Sequence[str], None] = 'c49a14b5d311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermemory', schema=None) as batch_op:
        batch_op.drop_column('is_onboarded')

    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_column('is_onboarded')

    with op.batch_alter_table('usermemory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarded', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###
