"""empty message

Revision ID: f28a491cc8eb
Revises: 960c239263d9
Create Date: 2026-02-23 21:00:53.281838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f28a491cc8eb'
down_revision: Union[str, Sequence[str], None] = '960c239263d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dayprogress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('current_topic_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dayprogress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dayprogress_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_dayprogress_user_id'), ['user_id'], unique=False)

    op.create_table('semesterstudyplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semesterstudyplan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semesterstudyplan_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_semesterstudyplan_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesterstudyplan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semesterstudyplan_user_id'))
        batch_op.drop_index(batch_op.f('ix_semesterstudyplan_scope'))

    op.drop_table('semesterstudyplan')
    with op.batch_alter_table('dayprogress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dayprogress_user_id'))
        batch_op.drop_index(batch_op.f('ix_dayprogress_scope'))

    op.drop_table('dayprogress')
    # ### end Alembic commands ###
