// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/payment/success": {
    params: {};
  };
  "/payment/cancel": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/payment/success" | "/payment/cancel" | "/register" | "/login" | "/*";
  };
  "routes/[payment].[success]._index.jsx": {
    id: "routes/[payment].[success]._index";
    page: "/payment/success";
  };
  "routes/[payment].[cancel]._index.jsx": {
    id: "routes/[payment].[cancel]._index";
    page: "/payment/cancel";
  };
  "routes/[register]._index.jsx": {
    id: "routes/[register]._index";
    page: "/register";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[payment].[success]._index": typeof import("./app/routes/[payment].[success]._index.jsx");
  "routes/[payment].[cancel]._index": typeof import("./app/routes/[payment].[cancel]._index.jsx");
  "routes/[register]._index": typeof import("./app/routes/[register]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};